version: '3.8'

services:
  # CONTENEDOR 1: La Base de Datos (PostgreSQL 16)
  postgresql_JMB:
    image: postgres:16
    container_name: postgresql_JMB
    restart: always
    ports:
      - "2345:5432" 
    env_file:
      - .env
    environment:
      POSTGRES_DB: gobierno_recu_jmb
      POSTGRES_USER: aaee_gobierno
      POSTGRES_PASSWORD: ${DB_PASSWORD} # Corrección: Usar el nombre de la variable del .env

  # CONTENEDOR 2: Tu aplicación Spring Boot
  api_rest:
    # RECUERDA: Cambia 'imoya-21' por TU usuario de GitHub en minúsculas
    image: ghcr.io/imoya-21/examen-recu-ra345:latest 
    container_name: api_rest_xxx
    restart: always
    ports:
      - "8080:8080"
    env_file:
      - .env
    depends_on:
      - postgresql_JMB # Debe coincidir exactamente con el nombre del servicio arriba
